# Generated by Django 2.0.2 on 2018-05-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_of_the_day', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercard',
            old_name='dat_card',
            new_name='date_card',
        ),
    ]
