# Generated by Django 2.0.2 on 2018-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_of_the_day', '0003_auto_20180507_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='date_used',
            field=models.DateField(),
        ),
    ]
