# Generated by Django 2.0.2 on 2018-05-07 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_of_the_day', '0004_auto_20180507_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='date_used',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
