# Generated by Django 2.0.2 on 2018-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_of_the_day', '0005_auto_20180507_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotcard',
            name='url_link',
        ),
        migrations.AddField(
            model_name='usercard',
            name='user_notes',
            field=models.TextField(blank=True),
        ),
    ]
