# Generated by Django 2.0.2 on 2018-05-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_of_the_day', '0006_auto_20180507_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='date_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to='tarot_of_the_day.TarotCard'),
        ),
    ]
