# Generated by Django 2.0.2 on 2018-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_of_the_day', '0007_auto_20180508_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='picture_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='date_used',
            field=models.DateField(default=''),
        ),
    ]
