# Generated by Django 2.0.2 on 2018-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesvideolinks',
            name='video_is_about',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
