# Generated by Django 2.0.2 on 2018-04-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='hour_of_birth',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
