# Generated by Django 2.0.2 on 2018-04-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0002_auto_20180429_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='horoscopes',
        ),
    ]
