# Generated by Django 2.0.2 on 2018-04-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0004_textsforuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user_visited_course',
        ),
        migrations.RemoveField(
            model_name='coursesvideolinks',
            name='courseID_video',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='CoursesVideoLinks',
        ),
    ]
