# Generated by Django 2.0.2 on 2018-05-23 20:46

from django.db import migrations, models
import user_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0006_auto_20180510_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=user_content.models.path_and_rename),
        ),
    ]
