# Generated by Django 2.0.2 on 2018-04-30 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500, unique=True)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('user_visited_course', models.ManyToManyField(related_name='user_visited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesVideoLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_link', models.URLField()),
                ('video_is_about', models.CharField(max_length=150)),
                ('courseID_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video', to='courses.Courses')),
            ],
        ),
    ]
